project:
  type: book
  output-dir: docs

book:
  title: "Emacs setup for LaTeX"
  author: "Moinul Islam"
  date: "today"
  chapters:
    - index.qmd
    - part: "MacOSX setup"
      chapters:
        - ch_1.qmd
        - ch_2.qmd
        - ch_3.qmd
        - ch_4.qmd
        - ch_5.qmd
        - ch_6.qmd
        - ch_7.qmd
        - ch_8.qmd
        - ch_9.qmd
        - ch_10.qmd
        - ch_11.qmd
    - part: "LinuxOS setup"
      chapters:
        - ch_13.qmd
        - ch_14.qmd
        - ch_15.qmd
        - ch_16.qmd
        - ch_17.qmd
        - ch_18.qmd
        - ch_12.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - darkly
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

